api:
  type: completion
  streaming: true
  headers: null
  slo_unit: null
  slo_tpot_header: null
  slo_ttft_header: null
  response_format: null
data:
  type: random
  path: null
  input_distribution:
    min: 2000
    max: 2100
    mean: 2048.0
    std_dev: 40.0
    total_count: 4321
    type: normal
    variance: null
    skew: 0.0
  output_distribution:
    min: 480
    max: 550
    mean: 512.0
    std_dev: 20.0
    total_count: 4321
    type: normal
    variance: null
    skew: 0.0
  shared_prefix: null
  trace: null
  otel_trace_replay: null
  conversation_replay: null
load:
  type: constant
  interval: 1.0
  stages:
  - rate: 5.0
    duration: 360
    num_requests: null
    concurrency_level: null
  - rate: 12.0
    duration: 360
    num_requests: null
    concurrency_level: null
  - rate: 5.0
    duration: 360
    num_requests: null
    concurrency_level: null
  sweep: null
  num_workers: 224
  worker_max_concurrency: 100
  worker_max_tcp_connections: 2500
  trace: null
  circuit_breakers: []
  request_timeout: null
  lora_traffic_split: null
  base_seed: 1785724038035
metrics: null
report:
  request_lifecycle:
    summary: true
    per_stage: true
    per_request: true
    per_adapter: true
    per_adapter_stage: false
    percentiles:
    - 0.1
    - 1.0
    - 5.0
    - 10.0
    - 25.0
    - 50.0
    - 75.0
    - 90.0
    - 95.0
    - 99.0
    - 99.9
  prometheus:
    summary: true
    per_stage: false
  session_lifecycle:
    summary: true
    per_stage: true
    per_session: false
  goodput: null
storage:
  local_storage:
    path: /requests/inference-perf-1785724033-d5lhav_1
    report_file_prefix: null
  google_cloud_storage: null
  simple_storage_service: null
server:
  type: vllm
  model_name: unsloth/Meta-Llama-3.1-8B-Instruct
  base_url: http://infra-llmdbench-inference-gateway-istio.dhl-wva-209.svc.cluster.local:80
  ignore_eos: true
  api_key: null
  cert_path: null
  key_path: null
tokenizer:
  pretrained_model_name_or_path: unsloth/Meta-Llama-3.1-8B-Instruct
  trust_remote_code: null
  token: null
circuit_breakers: null
