#!/usr/bin/env python3
"""Recover server-authoritative total token counts from vLLM /metrics scrapes.

Why this exists: on the 2026-08-07 ladder run the harness was OOMKilled while
serialising `per_request_lifecycle_metrics.json`, so the per-request trace -- the usual
input to the output-token correction -- is a 0-byte file. The aggregate
`summary_lifecycle_metrics.json` survived, but its output-token figures come from
inference-perf RE-TOKENIZING generated text, which it self-reports as wrong on 100% of
requests (`token_count_mismatches = 22200`).

vLLM's own counters are the ground truth and were scraped periodically per replica into
metrics/raw/. `vllm:generation_tokens_total` is monotonic PER POD and starts at 0 when a
pod is created, so total generated tokens = sum over pods of (max - min) observed. The
min term matters: pods that predate the load carry the pre-run probe's tokens, which must
not be attributed to the run.

Caveat this CANNOT fix: scrapes are periodic, so tokens generated by a pod after its last
scrape (notably a pod deleted on scale-down) are invisible. The result is therefore a
slight UNDER-count, not an over-count -- which is the safe direction for a denominator
used to prove the harness OVER-reports.

Input: output of
  grep -H -E '^vllm:(generation|prompt)_tokens_total' .../metrics/raw/*decode*_metrics.log

Usage: python3 server_token_truth.py [rawfile] [--requests N] [--seconds S]
"""
import re
import sys
from collections import defaultdict

# .../<deploy>-<rs>-<podsuffix>_<epoch>_metrics.log:vllm:<name>{...} <value>
LINE = re.compile(
    r"^.*/(?P<pod>[^/]+?)_(?P<epoch>\d+)_metrics\.log:"
    r"vllm:(?P<metric>generation|prompt)_tokens_total\{[^}]*\}\s+(?P<val>[\d.eE+]+)\s*$"
)


def main():
    argv = sys.argv[1:]
    pos = [a for a in argv if not a.startswith("-")]
    path = pos[0] if pos else "session-notes/scratch/vllm_tokens_raw.txt"

    def opt(name, default):
        return float(argv[argv.index(name) + 1]) if name in argv else default

    requests = opt("--requests", 22200)
    seconds = opt("--seconds", 2467.289220348932)

    # per pod, per metric: (min, max, n_scrapes, first_epoch, last_epoch)
    seen = defaultdict(lambda: defaultdict(list))
    skipped = 0
    for line in open(path, errors="replace"):
        m = LINE.match(line.strip())
        if not m:
            skipped += 1
            continue
        seen[m["pod"]][m["metric"]].append((int(m["epoch"]), float(m["val"])))

    if not seen:
        print(f"no vllm token counters parsed from {path}", file=sys.stderr)
        return 1

    totals = {"generation": 0.0, "prompt": 0.0}
    print(f"{'pod':<24} {'metric':<11} {'scrapes':>7} {'min':>12} {'max':>14} {'delta':>14}")
    for pod in sorted(seen):
        for metric in ("prompt", "generation"):
            pts = sorted(seen[pod].get(metric, []))
            if not pts:
                continue
            lo, hi = pts[0][1], pts[-1][1]
            # Monotonic counter; a decrease would mean the pod restarted mid-run and the
            # simple max-min would silently undercount. Flag rather than absorb it.
            nonmono = any(b[1] < a[1] for a, b in zip(pts, pts[1:]))
            delta = hi - lo
            totals[metric] += delta
            flag = "  <<< NON-MONOTONIC (pod restart?)" if nonmono else ""
            print(f"{pod[-24:]:<24} {metric:<11} {len(pts):>7} {lo:>12.0f} {hi:>14.0f} "
                  f"{delta:>14.0f}{flag}")

    print(f"\n{'':<24} {'TOTAL prompt':<11} {totals['prompt']:>36.0f}")
    print(f"{'':<24} {'TOTAL gen':<11} {totals['generation']:>36.0f}")

    print(f"\nrequests={requests:.0f}  window={seconds:.1f}s")
    for metric, label in (("prompt", "input"), ("generation", "output")):
        t = totals[metric]
        print(f"  server {label:<7} {t:>12.0f} tok  "
              f"= {t / requests:>8.1f} tok/req  = {t / seconds:>9.1f} tok/s")
    return 0


if __name__ == "__main__":
    sys.exit(main())
